apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-todo
  labels:
  {{- include "todo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.todo.replicas }}
  selector:
    matchLabels:
      app: todo
    {{- include "todo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: todo
      {{- include "todo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: {{ quote .Values.todo.todo.env.mongoUri }}
        - name: MONGO_DB
          value: {{ quote .Values.todo.todo.env.mongoDb }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - secretRef:
            name: mongodb-secret
        image: {{ .Values.todo.todo.image.repository }}:{{ .Values.todo.todo.image.apptag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.todo.todo.imagePullPolicy }}
        name: todo
        ports:
        - containerPort: 5000
        resources: {}
