version: '3'
services:
  app:
    build: .
    command: python app.py
    ports:
      - "8081:5000"
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=todo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
