kubernetesClusterDomain: cluster.local
todo:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    image:
      repository: mk51/todo-flask-app
      tag: fa19aa4b6ff9ba14e928d69e06cacd46c8adfeaa
    imagePullPolicy: Always
  type: NodePort
