kubernetesClusterDomain: cluster.local
todo:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    image:
      repository: mk51/todo-flask-app
      tag: e0ccb3b67a2d9954e2e34d6e33c2b5a4e9d45c11
    imagePullPolicy: Always
  type: NodePort
