kubernetesClusterDomain: cluster.local
todo:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    image:
      repository: mk51/todo-flask-app
      tag:fe4a7c87a0c8741e8b8c2d86a4aa183fab6a10e8
    imagePullPolicy: Always
  type: NodePort
