kubernetesClusterDomain: cluster.local
mongodb:
  mongodb:
    image:
      repository: mongo
      tag: 564babbdb20bd57ef48b9124f1cfe6f5e83a5f52
  ports:
  - port: 27017
    targetPort: 27017
  replicas: 1
  type: ClusterIP
  volumeClaims:
    mongodbStorage:
      requests:
        storage: 1Gi
mongodbSecret:
  mongoPassword: ""
  mongoUsername: ""
todo:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    env:
      mongoDb: todo
      mongoUri: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb.todo.svc.cluster.local:27017
    image:
      repository: mk51/todo-flask-app
      apptag: b2d002cbc6774182257b0e518e001506d22112dc
    imagePullPolicy: Always
  type: NodePort
