apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-chart.fullname" . }}-todo
  labels:
  {{- include "todo-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.todo.replicas }}
  selector:
    matchLabels:
      app: todo
    {{- include "todo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: todo
      {{- include "todo-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.todo.todo.image.repository }}:{{ .Values.todo.todo.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.todo.todo.imagePullPolicy }}
        name: todo
        ports:
        - containerPort: 5000
        resources: {}