# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: todo

---

# Secret for MongoDB authentication
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo
type: Opaque
data:
  MONGO_USERNAME: cm9vdA==  # base64-encoded "root"
  MONGO_PASSWORD: ZXhhbXBsZXBhc3N3b3Jk  # base64-encoded "examplepassword"

---

# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_PASSWORD
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  volumes:
  - name: mongodb-storage
    emptyDir: {}

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - image: mk51/todo-flask-app:ba939aeb0d2a9473bf4c97ecc9e75c428879ed58
        imagePullPolicy: Always
        name: todo
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017"
        - name: MONGO_DB
          value: "todo"
        envFrom:
        - secretRef:
            name: mongodb-secret

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: todo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 5000
    protocol: TCP
  selector:
    app: todo
