# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: todo

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - image: mk51/todo-flask-app:cfb6d272847ab9c80351b6885e734b2ec3df7c28
        imagePullPolicy: Always
        name: todo
        ports:
        - containerPort: 5000

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: todo
  namespace: todo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 5000
    protocol: TCP
  selector:
    app: todo
