kubernetesClusterDomain: cluster.local
mongodb:
  mongodb:
    image:
      repository: mongo
      tag: latest
  ports:
  - port: 27017
    targetPort: 27017
  replicas: 1
  type: ClusterIP
  volumeClaims:
    mongodbStorage:
      requests:
        storage: 1Gi
mongodbSecret:
  mongoPassword: ""
  mongoUsername: ""
todo:
  ports:
  - nodePort: 30300
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    env:
      mongoDb: todo
      mongoUri: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017
    image:
      repository: mk51/todo-flask-app
      apptag: 16b0e06c38e98e5efcd827dc58cdbb83294b2b7c
    imagePullPolicy: Always
  type: NodePort
