kubernetesClusterDomain: cluster.local
mongodb:
  mongodb:
    image:
      repository: mongo
      tag: latest
  ports:
  - port: 27017
    targetPort: 27017
  replicas: 1
  type: ClusterIP
  volumeClaims:
    mongodbStorage:
      requests:
        storage: 1Gi
mongodbSecret:
  mongoPassword: ""
  mongoUsername: ""
todo:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 5000
  replicas: 3
  todo:
    env:
      mongoDb: todo
      mongoUri: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017
    image:
      repository: mk51/todo-flask-app
      apptag: f7112d9193a6d31f1e3f5f3713426ae331d7c5a7
    imagePullPolicy: Always
  type: NodePort
