name: Docker

on:

  release:
    types: [published]

  push:
    # Publish `master` as Docker `master-latest` image
    # Publish for any branch as well
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  IMAGE: todo-flask-app
  REGISTRY: docker.io/mk51

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build .

  # Push image to Docker Hub
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $IMAGE -f Dockerfile .

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password "${{ secrets.DOCKER_PASS }}"


      - name: Push image for master branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          VERSION=${GITHUB_SHA}

          echo IMAGE=$IMAGE
          echo VERSION=$VERSION

          docker tag "$IMAGE" "$REGISTRY/$IMAGE:$VERSION"
          docker push "$REGISTRY/$IMAGE:$VERSION"

      - name: Update values.yaml
        run: |
          cd k8s/todo-chart
          sed -i 's|apptag:.*|apptag: '${{ github.sha }}'|' values.yaml
          git config --global user.name 'mikonoid'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push


      # - name: check for changes
      #   run: git status
      # - name: commit changed files
      #   run: |
      #     git config --local user.name "mikonoid"
      #     git add deployment.yml
      #     git commit -m "Auto updating deployment with tag ${GITHUB_SHA}"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
