name: Artifact
on:
  push:
    branches:
      - dev

jobs:
  test_pr:
    name: Test PR comment
    runs-on: ubuntu-latest
    steps:
    - name: Create a file
      run: echo ${{ github.ref }} > tag.txt
    - name: Accidentally upload to the same artifact via multiple jobs
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: ${{ github.workspace }}
    - name: Get artifact
      uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: ${{ github.workspace }}
    - name: Print the final result
      shell: bash
      run: |
        value=`cat tag.txt`
        echo The result is $valuet
