name: Get PR and comment
on:
  push:
    branches:
      - dev

jobs:
  test_pr:
    name: Test PR comment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: get_issue_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
            // Otherwise return issue number from commit
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          }
        result-encoding: string
    - name: Create a file
      run: echo ${{ github.ref }} > my_file.txt
    - name: Accidentally upload to the same artifact via multiple jobs
      uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: ${{ github.workspace }}
