name: Get PR
on:
  push:
    branches:
      - master


jobs:
  remove:
    name: Remove Feature Branch Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: Get Pull Request Number
        run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        shell: bash

      - name: show PR
        run: echo ${{ env.PULL_NUMBER }}
