name: Get PR
on:
  push:
    branches:
      - main


jobs:
  remove:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
      - name: get PR
        id: get_issue_number
        run: | 
          echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: Issue number
        run: echo '${{steps.get_issue_number.outputs.result}}'
    