name: Artifact
on:
  push:
    branches:
      - dev

jobs:
  tag-test:
    name: Artifact with tag
    runs-on: ubuntu-latest
    steps:
    - name: Create a file with tag
      run: echo ${{ github.ref }} > tag.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tag_artifact
        path: ${{ github.workspace }}/tag.txt
    - name: Get artifact
      uses: actions/download-artifact@v3
      with:
        name: tag_artifact
    - name: Print the final result
      shell: bash
      run: |
        value=`cat tag.txt`
        echo The result is $value
