name: Remove branch
on:
  push:
    branches:
      - master


jobs:
  remove:
    name: Remove Feature Branch Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
    - name: Set Stage Name
      run: |
        echo "testbranch"
        sleep 5
    - name: Get Pull Request Number
      id: pr
      run: |
        echo "The PR is: PR_NUMBER" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
