name: Get PR
on:
  push:
    branches:
      - main


jobs:
  remove:
    name: Remove Feature Branch Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
      - name: get PR
        id: get_issue_number
        run: | 
          echo "::set-env name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: Issue number
        run: echo '${{steps.get_issue_number.outputs.result}}'
    