name: Get PR and comment
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  test_pr:
    name: Test PR comment
    runs-on: ubuntu-latest
    # steps:
    #   - name: Get Pull Request Number
    #     run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
    #     shell: bash

    #   - name: show PR
    #     run: echo ${{ env.PULL_NUMBER }}
    steps:
    - uses: actions/github-script@v6
      # if: github.event.pull_request.merged == true
      id: get_issue_number
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (context.issue.number) {
            // Return issue number if present
            return context.issue.number;
          } else {
            // Otherwise return issue number from commit
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].number;
          }
        result-encoding: string
    - name: Issue number
      # if: github.event.pull_request.merged == true
      run: echo '${{steps.get_issue_number.outputs.result}}'
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      env: 
        commitmsg: ${GITHUB_SHA}
      # if: github.event.pull_request.merged == true
      with:
        message: |
          test $commitmsg :wave:
        pr_number: ${{steps.get_issue_number.outputs.result}}
        reactions: eyes, rocket
        comment_tag: test
    - name: Test task for master branch
      # if: github.ref == 'refs/heads/master'
      run: echo 'working'
