name: Remove branch
on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  remove:
    name: Remove Feature Branch Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
    steps:
    - name: Set Stage Name
      run: |
        echo "Remove branch"
        sleep 300

